DarkRP.RegisterSentences("kbrp_job_ranks", "de", {
	["policeRank1"] = "Polizeianwärter",
	["policeRank2"] = "Polizeimeister",
	["policeRank3"] = "Polizeiobermeister",
	["policeRank4"] = "Polizeihauptmeister",
	["policeRank5"] = "Polizeikommissar",
	["policeRank6"] = "Polizeioberkommissar",
	["policeRank7"] = "Polizeihauptkommissar",
	["securityRank1"] = "Azubi",
	["securityRank2"] = "Türsteher",
	["securityRank3"] = "Sicherheitsfachkraft",
	["firefighterRank1"] = "Feuerwehrmann/-frau-Anwärter",
	["firefighterRank2"] = "Feuerwehrmann/-frau",
	["firefighterRank3"] = "Oberfeuerwehrmann",
	["firefighterRank4"] = "Hauptfeuerwehrmanm",
	["firefighterRank5"] = "Löschmeister",
	["firefighterRank6"] = "Brandmeister",
	["firefighterRank7"] = "Oberbrandmeister",
	["firefighterRank8"] = "Kreisbrandmeister",
	["unknownRank"] = "Unbekannt",
	["cantChangePlayerXP"] = "Du kannst die XP von diesem Spieler nicht ändern!",
	["jobRequiredRank"] = "Du musst mindestens %s sein um %s zu werden.",
	["vehicleRequiredRank"] = "Du musst mindestens %s sein um auf dieses Fahrzeug zugreifen zu können."
})