DarkRP.RegisterSentences("kbrp_job_ranks", "fr", {
    ["policeRank1"] = "Gardien de la paix",
	["policeRank2"] = "Brigadier",
	["policeRank3"] = "Brigadier-chef",
	["policeRank4"] = "Major",
	["policeRank5"] = "Capitaine",
	["policeRank6"] = "Commandant",
	["policeRank7"] = "Commandant divisionnaire",
	["securityRank1"] = "Stagiaire",
	["securityRank2"] = "Recrue",
	["securityRank3"] = "Certifié",
	["firefighterRank1"] = "Sapeur 1ère classe",
	["firefighterRank2"] = "Caporal",
	["firefighterRank3"] = "Caporal-chef",
	["firefighterRank4"] = "Sergent",
	["firefighterRank5"] = "Sergent-chef",
	["firefighterRank6"] = "Adjudant",
	["firefighterRank7"] = "Adjudant-chef",
	["firefighterRank8"] = "Lieutenant",
	["unknownRank"] = "Inconnu",
	["cantChangePlayerXP"] = "Vous ne pouvez modifier l'XP de cette personne !",
	["jobRequiredRank"] = "Vous devez être au minimum %s pour devenir %s",
	["vehicleRequiredRank"] = "Vous devez être au minimum %s pour accéder à ce véhicule"
})