DarkRP.RegisterSentences("kbrp_truckjob", "fr", {
    ["truckJobNpcTitle"] = "Chauffeur Livreur",
	["npcUseCooldown"] = "Attendez un peu !",
	["returnVehicleButton"] = "Rentrer le Vehicule",
	["exitVehicleButton"] = "Sortir le Vehicule",
	["startInstructionTitle"] = "Pour commencer",
	["startInstructionDescriptionTakeVehicle"] = "Allez chercher votre véhicule au point indiqué",
	["startInstructionDescriptionTakeService"] = "Prenez votre service",
	["gotoLoadingPointInstruction"] = "Allez au point de chargement le plus rapidement possible !",
	["takeTrailerPointInstruction"] = "Allez chercher votre remorque pour commencer la livraison !",
	["enterInVehicleInstruction"] = "Rentrez dans votre vehicule pour continuer vos livraisons",
	["inDeliveryInstructionTitle"] = "Vous êtes en Livraison",
	["leaveServiceButton"] = "Quitter son service",
	["takeServiceButton"] = "Prendre son service",
	["actionUnavailable"] = "Cette action est indisponible pour le moment !",
	["noAvailableSpawnPlaces"] = "Il n'y a aucune place de disponible actuellement !",
	["takeNoOwnedTrailer"] = "Vous ne pouvez pas prendre la remorque d'un de vos collègues !",
	["tooFarLoadPoint"] = "Vous n'étiez pas a coté du point pour charger votre cargaison !",
	["truckLoaded"] = "Vous venez de charger votre camion !",
	["tooFarSellPoint"] = "Vous n'étiez pas a coté du point pour vendre votre cargaison !",
	["trailerDelivered"] = "Vous venez de livrez votre remorque vous avez gagné "
})