DarkRP.RegisterSentences("kbrp_truckjob", "de", {
    ["truckJobNpcTitle"] = "Fahrer/Lieferant",
	["npcUseCooldown"] = "Warte einen Moment!",
	["returnVehicleButton"] = "Fahrzeug einparken",
	["exitVehicleButton"] = "Fahrzeug ausparken",
	["startInstructionTitle"] = "Start",
	["startInstructionDescriptionTakeVehicle"] = "Hole dein Fahrzeug am markierten Punkt ab",
	["startInstructionDescriptionTakeService"] = "Starte deinen Dienst",
	["gotoLoadingPointInstruction"] = "Begebe dich so schnell wie möglich zum Ladepunkt!",
	["takeTrailerPointInstruction"] = "Hole deinen Anhänger ab, um mit der Lieferung zu beginnen!",
	["enterInVehicleInstruction"] = "Steige in dein Fahrzeug, um deine Lieferungen fortzusetzen.",
	["inDeliveryInstructionTitle"] = "Du befindest dich in einer Lieferung",
	["leaveServiceButton"] = "Dienst verlassen",
	["takeServiceButton"] = "Dienst antreten",
	["actionUnavailable"] = "Diese Aktion ist derzeit nicht verfügbar!",
	["noAvailableSpawnPlaces"] = "Derzeit gibt es keine freien Spawnplätze!",
	["takeNoOwnedTrailer"] = "Du kannst den Anhänger von einem Kollegen nicht übernehmen!",
	["tooFarLoadPoint"] = "Du bist zu weit vom Ladepunkt entfernt!",
	["truckLoaded"] = "Du hast deinen LKW erfolgreich beladen.",
	["tooFarSellPoint"] = "Du bist zu weit vom Verkaufspunkt entfernt!",
	["trailerDelivered"] = "Du hast deinen Anhänger erfolgreich abgeliefert und erhälst "
})