DarkRP.RegisterSentences("kbrp_seller", "fr", {
    ["npcMisconfigured"] = "Le NPC n'est pas configuré ! Veuillez contacter un administrateur !",
	["p99"] = "P99",
	["fiveSeven"] = "Five Seven",
	["mr96"] = "MR96",
	["desertEagle"] = "Desert Eagle",
	["lockpick"] = "Lockpick",
	["keypadCracker"] = "Keypad Cracker",
	["jewelleryPhone"] = "Telephone",
	["jewelleryHammer"] = "Marteau",
	["radio"] = "Radio",
	["serflex"] = "Serflex",
	["bag"] = "Sac",
	["lightKevlar"] = "Kevlar léger",
	["mediumKevlar"] = "Kevlar lourd",
	["npcTitle"] = "Vendeur divers",
	["alreadyGundealer"] = "Il y a déjà un vendeur d'armes en ville !",
	["entityPrice"] = "Prix : %s",
	["buyButton"] = "Acheter",
	["cantAfford"] = "Vous n'avez pas suffisament d'argent pour acheter cela !",
	["errorOccured"] = "Une erreur c'est produite, veuillez contacter un administrateur !",
	["invalidItem"] = "Cet item n'est pas vendu par le pnj, ne tente pas d'exploit !",
	["npcTooFar"] = "Vous devez être plus proche du NPC !",
	["itemBought"] = "Vous venez de payer un(e) %s pour %s"
})
