DarkRP.RegisterSentences("kbrp_ban_system", "fr", {
    ["year"] = "année",
    ["yearPlural"] = "années",
	["month"] = "mois",
	["monthPlural"] = "mois",
	["week"] = "semaine",
	["weekPlural"] = "semaines",
	["day"] = "jour",
	["dayPlural"] = "jours",
	["hour"] = "heure",
	["hourPlural"] = "heures",
	["minut"] = "minute",
	["minutPlural"] = "minutes",
	["second"] = "seconde",
	["secondPlural"] = "secondes",
	["tempBanInstruction"] = "Vous êtes banni temporairement",
	["bannedInstruction"] = "Vous êtes banni",
	["instructionDescription"] = "Nous sommes triste de vous voir dans nos cachots !",
	["instructionDescription2"] = "Motif : %s",
	["instructionDescription22"] = "Temps d'attente : %s",
	["permanent"] = "PERMANENT",
	["waitingUnban"] = "En attente de débanissement",
	["cantChangeJob"] = "Vous êtes banni du serveur, vous ne pouvez donc pas changer de métier !",
	["invalidReason"] = "Aucune raison spécifique",
	["cantSpawnEntityIfBanned"] = "Vous ne pouvez pas faire spawn d'entité dans la salle des bannis !"
})