DarkRP.RegisterSentences("kbrp_ban_system", "de", {
    ["year"] = "Jahr",
    ["yearPlural"] = "Jahre",
	["month"] = "Monat",
	["monthPlural"] = "Monate",
	["week"] = "Woche",
	["weekPlural"] = "Wochen",
	["day"] = "Tag",
	["dayPlural"] = "Tage",
	["hour"] = "Stunde",
	["hourPlural"] = "Stunden",
	["minut"] = "Minute",
	["minutPlural"] = "Minuten",
	["second"] = "Sekunde",
	["secondPlural"] = "Sekunden",
	["tempBanInstruction"] = "Du wirst vorübergehend gebannt",
	["bannedInstruction"] = "Du bist gebannt",
	["instructionDescription"] = "Wir finden es schade das es so kommen musste...",
	["instructionDescription2"] = "Grund : %s",
	["instructionDescription22"] = "Zeit bis zur Entbannung : ",
	["permanent"] = "PERMANENT",
	["waitingUnban"] = "Warte auf die Entbannung",
	["cantChangeJob"] = "Du bist von Kobralost Roleplay gebannt und darfst deshalb deinen Beruf nicht wechseln!",
	["invalidReason"] = "Kein spezifischer Grund",
	["cantSpawnEntityIfBanned"] = "Du bist von Kobralost Roleplay gebannt und darfst deshalb keine Entitys spawnen!"
})