DarkRP.RegisterSentences("kbrp_statut", "fr", {
    ["serverInformationEmbedTitle"] = "Information du serveur",
	["serverNameFieldName"] = "🦉 Nom du serveur",
	["onlineServerFFieldName"] = "🟢 Statut du serveur",
	["offlineServerFieldName"] = "🔴 Statut du serveur",
	["onlineServerFieldDescription"] = "En ligne",
	["offlineServerFieldDescription"] = "Hors Ligne",
	["serverMapFieldName"] = "🏠 Map actuelle",
	["serverCollectionFieldName"] = "📚 Collection du serveur",
	["serverCollectionFieldDescription"] = "[Cliquez ici](https://kobralost-rp.fr/addons)",
	["dashboardFieldName"] = "💎 Dashboard du serveur",
	["dashboardFieldDescription"] = "[Cliquez ici](https://dashboard.kobralost-rp.fr/)",
	["joinServerFieldName"] = "🌐 Rejoindre le serveur",
	["joinServerFieldDescription"] = "steam://connect/play.kobralost-rp.fr",
	["onlineSttaffPrefix"] = "🟢",
	["staffNotInServicePrefix"] = "🟠",
	["playersAmountFieldName"] = "🧑‍🤝‍🧑 Nombre de joueurs",
	["staffAmountFieldName"] = "💎 Staffs en service",
	["lackOfStaffText"] = "(**Manque %s staff**)",
	["staffStatusEmbedFieldName"] = "👁️ Statut des staffs",
	["ticketsInQueueFieldName"] = "📨 Tickets en attente",
	["playersInQueueFieldName"] = "🙋 File d'attente",
	["playersInQueueFieldDescription"] = "%s joueurs en attente",
	["playerQueueDisabled"] = "Désactivée"
})